[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.mbstring",
  "php83Extensions.xml",
  "php83Extensions.curl",
  "php83Extensions.zip",
  "php83Extensions.pdo_mysql"
]
